# Generated by Django 4.2.2 on 2023-06-11 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Desc', models.TextField(max_length=1024, verbose_name='Description')),
                ('AssignedTo', models.CharField(default='None', max_length=256, verbose_name='Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TaskGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalID', models.IntegerField(default=0)),
                ('Title', models.CharField(max_length=256)),
                ('CStatusID', models.IntegerField(default=0, verbose_name='Current status ID')),
                ('EStatusID', models.IntegerField(default=1, verbose_name='Max status ID')),
                ('TaskRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSMain.taskitem')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSMain.taskitem')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
